"use client";

import Link from "next/link";
import { useState } from "react";
import { submitIdea, pollUntilDone, AnalysisResult } from "@/lib/api";
import ScoreRadar from "@/components/ScoreRadar";
import ResultCard from "@/components/ResultCard";

type AppState = "idle" | "loading" | "done" | "error";

export default function Home() {
  const [idea, setIdea] = useState("");
  const [state, setState] = useState<AppState>("idle");
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [statusMsg, setStatusMsg] = useState("");
  const [error, setError] = useState("");

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!idea.trim() || idea.length < 20) return;

    setState("loading");
    setResult(null);
    setError("");
    setStatusMsg("Queuing analysis...");

    try {
      const id = await submitIdea(idea.trim());
      setStatusMsg(
        "Agents are running market, competitive, and monetization analysis...",
      );
      const res = await pollUntilDone(id);

      if (res.status === "failed") {
        setError(res.error ?? "Analysis failed.");
        setState("error");
      } else {
        setResult(res);
        setState("done");
      }
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : "Unexpected error.");
      setState("error");
    }
  }

  return (
    <main className="relative overflow-x-clip px-4 py-10 sm:px-6 lg:px-8">
      <div className="pointer-events-none absolute inset-0 opacity-60">
        <div className="absolute -left-20 top-16 h-56 w-56 rounded-full bg-emerald-400/15 blur-3xl" />
        <div className="absolute -right-8 top-36 h-72 w-72 rounded-full bg-cyan-400/15 blur-3xl" />
      </div>

      <section className="relative mx-auto w-full max-w-5xl space-y-7">
        <header className="rounded-3xl border border-slate-300/15 bg-slate-950/55 p-6 backdrop-blur md:p-9">
          <p className="mb-3 inline-flex rounded-full border border-emerald-400/40 bg-emerald-400/10 px-3 py-1 text-[11px] font-semibold uppercase tracking-[0.22em] text-emerald-300">
            Idea Validation Lab
          </p>
          <h1 className="text-3xl font-semibold leading-tight text-slate-50 md:text-5xl">
            Idea Stress-Test Engine
          </h1>
          <p className="mt-3 max-w-3xl text-sm leading-relaxed text-slate-300 md:text-base">
            Multi-agent analysis across market reality, competitive pressure,
            monetization fit, and downside resilience. Grounded in live search
            data — not static opinions.
          </p>
          <p className="mt-3 text-xs leading-relaxed text-slate-400 max-w-2xl">
            Free to use.{" "}
            <span className="text-slate-300 font-medium">
              2 analyses per device per day.
            </span>{" "}
            Results are generated by AI and reflect available public information
            at the time of analysis. They are intended as a structured starting
            point, not a substitute for domain expertise, primary research, or
            professional advice.
          </p>
          <div className="mt-5 flex flex-wrap gap-3">
            <Link
              href="/about"
              className="rounded-full border border-slate-200/15 bg-slate-900/50 px-4 py-2 text-xs font-semibold uppercase tracking-[0.14em] text-slate-200 transition hover:border-emerald-300/40 hover:text-emerald-200"
            >
              Public project info
            </Link>
            <Link
              href="/about#contributions"
              className="rounded-full border border-cyan-300/25 bg-cyan-400/10 px-4 py-2 text-xs font-semibold uppercase tracking-[0.14em] text-cyan-100 transition hover:border-cyan-200/45 hover:bg-cyan-400/15"
            >
              Contribute or give feedback
            </Link>
          </div>
        </header>

        <form
          onSubmit={handleSubmit}
          className="rounded-3xl border border-slate-300/15 bg-[rgba(7,14,22,0.82)] p-5 backdrop-blur md:p-7"
        >
          <label className="mb-2 block text-xs font-semibold uppercase tracking-[0.16em] text-slate-300">
            Describe Your Business Idea
          </label>
          <textarea
            value={idea}
            onChange={(e) => setIdea(e.target.value)}
            placeholder="Example: AI-first SaaS that auto-reconciles invoices for small accounting firms."
            rows={6}
            maxLength={2000}
            disabled={state === "loading"}
            className="w-full rounded-2xl border border-slate-500/35 bg-slate-900/70 p-4 text-sm leading-relaxed text-slate-100 placeholder:text-slate-500 focus:border-cyan-300/50 focus:outline-none focus:ring-2 focus:ring-cyan-300/20 disabled:cursor-not-allowed disabled:opacity-70"
          />

          <div className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
            <span className="font-[var(--font-mono)] text-xs text-slate-300/90">
              {idea.length}/2000 chars (min 20)
            </span>
            <button
              type="submit"
              disabled={state === "loading" || idea.length < 20}
              className="rounded-xl border border-emerald-300/40 bg-gradient-to-r from-emerald-400 to-cyan-400 px-5 py-2.5 text-sm font-semibold text-slate-950 shadow-[0_10px_30px_rgba(34,197,94,0.28)] transition hover:brightness-110 disabled:cursor-not-allowed disabled:opacity-45 disabled:hover:brightness-100"
            >
              {state === "loading" ? "Analyzing..." : "Stress-Test Idea"}
            </button>
          </div>
        </form>

        <section className="grid gap-4 lg:grid-cols-[1.25fr_0.95fr]">
          <div className="rounded-3xl border border-slate-300/15 bg-slate-950/50 p-5 backdrop-blur md:p-6">
            <p className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-400">
              Contact for collaboration or support
            </p>
            <h2 className="mt-2 text-2xl font-semibold text-slate-50">
              Building this in public and actively looking for support.
            </h2>
            <p className="mt-3 max-w-2xl text-sm leading-relaxed text-slate-300">
              If you want to contribute code, share product feedback, explore
              partnerships, reach out directly. The project is being built for
              public use and needs practical help from operators, researchers,
              and early supporters.
            </p>
          </div>
          <div className="rounded-3xl border border-emerald-300/20 bg-gradient-to-br from-emerald-400/12 to-cyan-400/12 p-5 md:p-6">
            <p className="text-xs font-semibold uppercase tracking-[0.16em] text-emerald-200/90">
              Open Source
            </p>
            <p className="mt-3 text-xl font-semibold text-emerald-300 break-all">
              Community contributions welcome
            </p>
            <p className="mt-3 text-sm leading-relaxed text-slate-200/90">
              Start with the project overview, contribution guide, and privacy
              notes linked below.
            </p>
            <div className="mt-5 flex flex-wrap gap-3">
              <Link
                href="/about"
                className="rounded-full border border-cyan-300/30 bg-cyan-400/10 px-4 py-2 text-xs font-semibold uppercase tracking-[0.14em] text-cyan-100 transition hover:border-cyan-200/45 hover:bg-cyan-400/15"
              >
                Project overview
              </Link>
              <Link
                href="/about#contributions"
                className="rounded-full border border-slate-200/20 bg-slate-950/45 px-4 py-2 text-xs font-semibold uppercase tracking-[0.14em] text-slate-100 transition hover:border-emerald-300/35 hover:text-emerald-200"
              >
                Ways to contribute
              </Link>
              <Link
                href="/privacy"
                className="rounded-full border border-slate-200/20 bg-slate-950/45 px-4 py-2 text-xs font-semibold uppercase tracking-[0.14em] text-slate-100 transition hover:border-emerald-300/35 hover:text-emerald-200"
              >
                Privacy notes
              </Link>
            </div>
            <p className="mt-4 block break-all text-sm font-medium text-cyan-100">
              The public project docs explain local setup, contribution flow,
              and deployment.
            </p>
          </div>
        </section>

        {state === "loading" && (
          <div className="rounded-2xl border border-cyan-300/20 bg-cyan-400/10 px-4 py-3 text-sm text-cyan-100">
            {statusMsg}
          </div>
        )}

        {state === "error" && (
          <div className="rounded-2xl border border-rose-400/40 bg-rose-500/10 px-4 py-3 text-sm text-rose-100">
            {error}
          </div>
        )}

        {state === "done" && result && (
          <section className="space-y-6">
            {result.viability && (
              <div className="rounded-3xl border border-emerald-300/20 bg-slate-950/60 p-6 backdrop-blur md:p-8">
                <p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-400">
                  Viability Score
                </p>
                <div className="mt-2 flex flex-col gap-5 md:flex-row md:items-center md:justify-between">
                  <div>
                    <p className="text-6xl font-bold text-emerald-300 md:text-7xl">
                      {result.viability.scaled_score}
                    </p>
                    <p className="font-[var(--font-mono)] text-xs text-slate-400">
                      out of 100
                    </p>
                  </div>
                  <div className="mx-auto w-full max-w-sm">
                    <ScoreRadar breakdown={result.viability.breakdown} />
                  </div>
                </div>
              </div>
            )}

            <div className="grid gap-5 md:grid-cols-2">
              {result.market && (
                <ResultCard title="Market Analysis">
                  <Stat label="TAM" value={result.market.tam_estimate_range} />
                  <Stat
                    label="Growth"
                    value={result.market.market_growth_rate}
                  />
                  <Stat label="Trend" value={result.market.trend_direction} />
                  <Stat
                    label="Saturation"
                    value={`${result.market.saturation_score}/10`}
                  />
                  <Stat
                    label="Confidence"
                    value={`${Math.round(result.market.confidence * 100)}%`}
                  />
                </ResultCard>
              )}

              {result.competitive && (
                <ResultCard title="Competitive Landscape">
                  <Stat
                    label="Moat"
                    value={`${result.competitive.moat_score}/10`}
                  />
                  <Stat
                    label="Differentiation"
                    value={`${result.competitive.differentiation_strength}/10`}
                  />
                  <Stat
                    label="Entry Barrier"
                    value={`${result.competitive.entry_barrier_score}/10`}
                  />
                  {result.competitive.red_flags.length > 0 && (
                    <div className="mt-3 space-y-1">
                      <p className="text-[11px] font-semibold uppercase tracking-[0.12em] text-rose-200/80">
                        Red Flags
                      </p>
                      {result.competitive.red_flags.map((flag, i) => (
                        <p
                          key={i}
                          className="text-xs leading-relaxed text-rose-100/90"
                        >
                          {flag}
                        </p>
                      ))}
                    </div>
                  )}
                </ResultCard>
              )}

              {result.monetization && (
                <ResultCard title="Monetization">
                  <Stat
                    label="Willingness to Pay"
                    value={`${result.monetization.willingness_to_pay_score}/10`}
                  />
                  <Stat
                    label="CAC Risk"
                    value={`${result.monetization.cac_risk_score}/10`}
                  />
                  <Stat
                    label="LTV Feasibility"
                    value={`${result.monetization.ltv_feasibility}/10`}
                  />
                  <Stat
                    label="Difficulty"
                    value={`${result.monetization.monetization_difficulty}/10`}
                  />
                </ResultCard>
              )}

              {result.audit && (
                <ResultCard
                  title={`Audit Confidence ${result.audit.overall_confidence_score}%`}
                >
                  {result.audit.uncertainty_flags.length > 0 ? (
                    <div className="space-y-1.5">
                      {result.audit.uncertainty_flags.map((flag, i) => (
                        <p
                          key={i}
                          className="text-xs leading-relaxed text-amber-100/90"
                        >
                          {flag}
                        </p>
                      ))}
                    </div>
                  ) : (
                    <p className="text-xs text-slate-400">
                      No major uncertainty flags.
                    </p>
                  )}
                  {result.audit.unsupported_claims.length > 0 && (
                    <div className="mt-3 space-y-1">
                      {result.audit.unsupported_claims.map((claim, i) => (
                        <p
                          key={i}
                          className="text-xs leading-relaxed text-slate-300"
                        >
                          Unverified claim: {claim}
                        </p>
                      ))}
                    </div>
                  )}
                </ResultCard>
              )}
            </div>

            <p className="px-1 font-[var(--font-mono)] text-[11px] uppercase tracking-[0.12em] text-slate-400/90">
              {result.search_snippets_used} snippets used | Analysis ID{" "}
              {result.id}
            </p>
          </section>
        )}
      </section>
    </main>
  );
}

function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between gap-3 border-b border-slate-300/10 py-2 text-sm">
      <span className="text-slate-400">{label}</span>
      <span className="text-right font-medium text-slate-100">{value}</span>
    </div>
  );
}
